'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.34209
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Функциональные возможности автосохранения My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("68")>  _
        Public Property eurCource() As Decimal
            Get
                Return CType(Me("eurCource"),Decimal)
            End Get
            Set
                Me("eurCource") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.4")>  _
        Public Property koeffkat1() As Decimal
            Get
                Return CType(Me("koeffkat1"),Decimal)
            End Get
            Set
                Me("koeffkat1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("калькулятор цен 2013.xls")>  _
        Public Property filename() As String
            Get
                Return CType(Me("filename"),String)
            End Get
            Set
                Me("filename") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("диаграмма")>  _
        Public Property sheetname() As String
            Get
                Return CType(Me("sheetname"),String)
            End Get
            Set
                Me("sheetname") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property fullPath() As String
            Get
                Return CType(Me("fullPath"),String)
            End Get
            Set
                Me("fullPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property Nakladnye() As Decimal
            Get
                Return CType(Me("Nakladnye"),Decimal)
            End Get
            Set
                Me("Nakladnye") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property fullPathPrice() As String
            Get
                Return CType(Me("fullPathPrice"),String)
            End Get
            Set
                Me("fullPathPrice") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Рассчет продажи 2015.xlsx")>  _
        Public Property filenamePrice() As String
            Get
                Return CType(Me("filenamePrice"),String)
            End Get
            Set
                Me("filenamePrice") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Тарифы")>  _
        Public Property sheetnamePrice_tariff() As String
            Get
                Return CType(Me("sheetnamePrice_tariff"),String)
            End Get
            Set
                Me("sheetnamePrice_tariff") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Цены")>  _
        Public Property sheetnamePrice_Prices() As String
            Get
                Return CType(Me("sheetnamePrice_Prices"),String)
            End Get
            Set
                Me("sheetnamePrice_Prices") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Выплаты")>  _
        Public Property sheetnamePrice_Pays() As String
            Get
                Return CType(Me("sheetnamePrice_Pays"),String)
            End Get
            Set
                Me("sheetnamePrice_Pays") = value
            End Set
        End Property
        
        '''<summary>
        '''Допустимая оптовая скидка
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Допустимая оптовая скидка"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property WholeMaximumDiscount() As Decimal
            Get
                Return CType(Me("WholeMaximumDiscount"),Decimal)
            End Get
            Set
                Me("WholeMaximumDiscount") = value
            End Set
        End Property
        
        '''<summary>
        '''расходы продавца в % от общей суммы расходов
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("расходы продавца в % от общей суммы расходов"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("25")>  _
        Public Property SalerCost() As Decimal
            Get
                Return CType(Me("SalerCost"),Decimal)
            End Get
            Set
                Me("SalerCost") = value
            End Set
        End Property
        
        '''<summary>
        '''средние выставочные накладные
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("средние выставочные накладные"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property ExhibitionCost() As Decimal
            Get
                Return CType(Me("ExhibitionCost"),Decimal)
            End Get
            Set
                Me("ExhibitionCost") = value
            End Set
        End Property
        
        '''<summary>
        '''тариф обналички PAYPAL
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("тариф обналички PAYPAL"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10.5")>  _
        Public Property PayPalFee_Full() As Decimal
            Get
                Return CType(Me("PayPalFee_Full"),Decimal)
            End Get
            Set
                Me("PayPalFee_Full") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.PriceCalculator.My.MySettings
            Get
                Return Global.PriceCalculator.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
