'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.34209
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Public NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Функциональные возможности автосохранения My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CurrentPhotoPath() As String
            Get
                Return CType(Me("CurrentPhotoPath"),String)
            End Get
            Set
                Me("CurrentPhotoPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("d:\orders_2010\")>  _
        Public Property OrdersPath() As String
            Get
                Return CType(Me("OrdersPath"),String)
            End Get
            Set
                Me("OrdersPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <s"& _ 
            "tring>Литвинов</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>Анастасия</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>Пахом</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ArrayOfString>")>  _
        Public Property PhotoWokers() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("PhotoWokers"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("PhotoWokers") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1600")>  _
        Public Property OptimizeImageWight() As Integer
            Get
                Return CType(Me("OptimizeImageWight"),Integer)
            End Get
            Set
                Me("OptimizeImageWight") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ThisIsMarkerFile.xml")>  _
        Public ReadOnly Property PhotoDriveFileMarkerName() As String
            Get
                Return CType(Me("PhotoDriveFileMarkerName"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DATABASES\DataFossil.xml")>  _
        Public Property DataFilePath() As String
            Get
                Return CType(Me("DataFilePath"),String)
            End Get
            Set
                Me("DataFilePath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DATABASES\tempDATA\DatadboPhotoStore.xml")>  _
        Public Property xmldboPhotoStorePath() As String
            Get
                Return CType(Me("xmldboPhotoStorePath"),String)
            End Get
            Set
                Me("xmldboPhotoStorePath") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("data source=v0ecxr50yd.database.windows.net;initial catalog=DBREADYSAMPLE;persist"& _ 
            " security info=True;user id=foto;password=Asaphus2009;MultipleActiveResultSets=T"& _ 
            "rue;App=EntityFramework")>  _
        Public ReadOnly Property dbReadySampleConnectionString() As String
            Get
                Return CType(Me("dbReadySampleConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("data source=v0ecxr50yd.database.windows.net,1433;initial catalog=DBOPHOTO;user id"& _ 
            "=foto;password=Asaphus2009;multipleactiveresultsets=True;App=EntityFramework")>  _
        Public ReadOnly Property dboPhotoConnectionString() As String
            Get
                Return CType(Me("dboPhotoConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <s"& _ 
            "tring>NEWCOMP\TRILBONE</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>AZURE</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ArrayOfString>")>  _
        Public Property DbServersNames() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("DbServersNames"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("DbServersNames") = value
            End Set
        End Property
        
        '''<summary>
        '''папка для поиска фоток фотоменеджером
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("папка для поиска фоток фотоменеджером"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("d:\ОБРАБОТАННЫЕ\")>  _
        Public Property PhotoManagerStarUpFolder() As String
            Get
                Return CType(Me("PhotoManagerStarUpFolder"),String)
            End Get
            Set
                Me("PhotoManagerStarUpFolder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("d:\размеры_андрей.xlsx")>  _
        Public Property ExcelBookPath() As String
            Get
                Return CType(Me("ExcelBookPath"),String)
            End Get
            Set
                Me("ExcelBookPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ArhivePhotoPath() As String
            Get
                Return CType(Me("ArhivePhotoPath"),String)
            End Get
            Set
                Me("ArhivePhotoPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property encoding() As String
            Get
                Return CType(Me("encoding"),String)
            End Get
            Set
                Me("encoding") = value
            End Set
        End Property
        
        '''<summary>
        '''доступные к оформлению сотрудники
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("доступные к оформлению сотрудники"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <s"& _ 
            "tring>Анастасия</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>Кирилл</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>Литвинов</string>"& _ 
            ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>Пахом</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ArrayOfString>")>  _
        Public Property Wokers() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Wokers"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("Wokers") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <s"& _ 
            "tring>S2</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>S3 (8-2712)</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>S3x4 (8-2712-1)</st"& _ 
            "ring>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>S4 (8-2710)</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>S4x45 (8-2710-1)</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <s"& _ 
            "tring>S4x5 (8-2710-2)</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>S5 (8-2715)</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>S5x45 "& _ 
            "(8-2715-1)</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>S6 (8-2716)</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>S6x75 (8-2716-1)<"& _ 
            "/string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>S6x9 (8-2716-2)</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>S93x85 (8-2717)</string>"& _ 
            ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>S93x125 (8-2717-1)</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>S125x75 (8-2714)</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</"& _ 
            "ArrayOfString>")>  _
        Public Property PaperBoxTypes() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("PaperBoxTypes"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("PaperBoxTypes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property dx() As Integer
            Get
                Return CType(Me("dx"),Integer)
            End Get
            Set
                Me("dx") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property dy() As Integer
            Get
                Return CType(Me("dy"),Integer)
            End Get
            Set
                Me("dy") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TemplateFolderPath() As String
            Get
                Return CType(Me("TemplateFolderPath"),String)
            End Get
            Set
                Me("TemplateFolderPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LabelDrawPhotoPath() As String
            Get
                Return CType(Me("LabelDrawPhotoPath"),String)
            End Get
            Set
                Me("LabelDrawPhotoPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("UserPermission.xml")>  _
        Public Property UserFileName() As String
            Get
                Return CType(Me("UserFileName"),String)
            End Get
            Set
                Me("UserFileName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("QL-710w")>  _
        Public Property DefaultPrinterName() As String
            Get
                Return CType(Me("DefaultPrinterName"),String)
            End Get
            Set
                Me("DefaultPrinterName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Agents.xml")>  _
        Public Property AgentFileName() As String
            Get
                Return CType(Me("AgentFileName"),String)
            End Get
            Set
                Me("AgentFileName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("e:\GoogleDrive_fossilcollecting\My Trees\")>  _
        Public Property TreeFolderPath() As String
            Get
                Return CType(Me("TreeFolderPath"),String)
            End Get
            Set
                Me("TreeFolderPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("trilbone")>  _
        Public Property SiteAccount() As String
            Get
                Return CType(Me("SiteAccount"),String)
            End Get
            Set
                Me("SiteAccount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("49.92")>  _
        Public Property RateUSD() As Decimal
            Get
                Return CType(Me("RateUSD"),Decimal)
            End Get
            Set
                Me("RateUSD") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("55.08")>  _
        Public Property RateEUR() As Decimal
            Get
                Return CType(Me("RateEUR"),Decimal)
            End Get
            Set
                Me("RateEUR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("data source=wisteria.arvixe.com;initial catalog=nopDB;persist security info=True;"& _ 
            "user id=fotoNC;password=Asaphus2009;MultipleActiveResultSets=True;App=EntityFram"& _ 
            "ework")>  _
        Public Property dbNopConnectionString() As String
            Get
                Return CType(Me("dbNopConnectionString"),String)
            End Get
            Set
                Me("dbNopConnectionString") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property MailInsectionFee() As Decimal
            Get
                Return CType(Me("MailInsectionFee"),Decimal)
            End Get
            Set
                Me("MailInsectionFee") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property EbayQuery() As Boolean
            Get
                Return CType(Me("EbayQuery"),Boolean)
            End Get
            Set
                Me("EbayQuery") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("data source=wisteria.arvixe.com;initial catalog=MyTrees;persist security info=Tru"& _ 
            "e;user id=fotoNC;password=Asaphus2009;MultipleActiveResultSets=True;App=EntityFr"& _ 
            "amework")>  _
        Public Property dbMyTreesConnectionString() As String
            Get
                Return CType(Me("dbMyTreesConnectionString"),String)
            End Get
            Set
                Me("dbMyTreesConnectionString") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Рассчет продажи 2015.xlsx")>  _
        Public Property PriceFileName() As String
            Get
                Return CType(Me("PriceFileName"),String)
            End Get
            Set
                Me("PriceFileName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("калькулятор цен 2013")>  _
        Public Property CalcFileName() As String
            Get
                Return CType(Me("CalcFileName"),String)
            End Get
            Set
                Me("CalcFileName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ExcelEnabled() As Boolean
            Get
                Return CType(Me("ExcelEnabled"),Boolean)
            End Get
            Set
                Me("ExcelEnabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Maps.xml")>  _
        Public Property MappingFileName() As String
            Get
                Return CType(Me("MappingFileName"),String)
            End Get
            Set
                Me("MappingFileName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property GdriveFolderPath() As String
            Get
                Return CType(Me("GdriveFolderPath"),String)
            End Get
            Set
                Me("GdriveFolderPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property FtpModeActive() As Boolean
            Get
                Return CType(Me("FtpModeActive"),Boolean)
            End Get
            Set
                Me("FtpModeActive") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://api.ebay.com/wsapi")>  _
        Public ReadOnly Property Service_com_ebay_developer_eBayAPIInterfaceService() As String
            Get
                Return CType(Me("Service_com_ebay_developer_eBayAPIInterfaceService"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Service.My.MySettings
            Get
                Return Global.Service.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
