
'------------------------------------------------------------------------------
' <auto-generated>
'    Этот код был создан из шаблона.
'
'    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
'    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("953889fb-b554-400a-804f-d66468378351")>
#Region "Метаданные связи EDM"
<Assembly: EdmRelationshipAttribute("ModelSampleList", "ListLineSampleList", "ListLine", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(ListLine), "SampleList", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(SampleList), True)>
<Assembly: EdmRelationshipAttribute("ModelSampleList", "ListTypeSampleList", "ListType", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(ListType), "SampleList", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(SampleList), True)>
<Assembly: EdmRelationshipAttribute("ModelSampleList", "SampleInListSampleParameter", "SampleInList", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(SampleInList), "SampleParameter", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(SampleParameter), True)>
<Assembly: EdmRelationshipAttribute("ModelSampleList", "SampleListSampleListParameter", "SampleList", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(SampleList), "SampleListParameter", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(SampleListParameter), True)>
<Assembly: EdmRelationshipAttribute("ModelSampleList", "SampleInListSampleAndList", "SampleInList", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(SampleInList), "SampleAndList", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(SampleAndList), True)>
<Assembly: EdmRelationshipAttribute("ModelSampleList", "SampleListSampleAndList", "SampleList", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(SampleList), "SampleAndList", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(SampleAndList), True)>

#End Region

#Region "Контексты"

''' <summary>
''' Нет доступной документации по метаданным.
''' </summary>
Public Partial Class ModelSampleListContainer
    Inherits ObjectContext

    #Region "Конструкторы"

    ''' <summary>
    ''' Инициализирует новый объект ModelSampleListContainer, используя строку соединения из раздела "ModelSampleListContainer" файла конфигурации приложения.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=ModelSampleListContainer", "ModelSampleListContainer")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Инициализация нового объекта ModelSampleListContainer.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "ModelSampleListContainer")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Инициализация нового объекта ModelSampleListContainer.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "ModelSampleListContainer")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Разделяемые методы"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "Свойства ObjectSet"

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    Public ReadOnly Property SampleListCollection() As ObjectSet(Of SampleList)
        Get
            If (_SampleListCollection Is Nothing) Then
                _SampleListCollection = MyBase.CreateObjectSet(Of SampleList)("SampleListCollection")
            End If
            Return _SampleListCollection
        End Get
    End Property

    Private _SampleListCollection As ObjectSet(Of SampleList)

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    Public ReadOnly Property ListLineCollection() As ObjectSet(Of ListLine)
        Get
            If (_ListLineCollection Is Nothing) Then
                _ListLineCollection = MyBase.CreateObjectSet(Of ListLine)("ListLineCollection")
            End If
            Return _ListLineCollection
        End Get
    End Property

    Private _ListLineCollection As ObjectSet(Of ListLine)

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    Public ReadOnly Property ListTypeCollection() As ObjectSet(Of ListType)
        Get
            If (_ListTypeCollection Is Nothing) Then
                _ListTypeCollection = MyBase.CreateObjectSet(Of ListType)("ListTypeCollection")
            End If
            Return _ListTypeCollection
        End Get
    End Property

    Private _ListTypeCollection As ObjectSet(Of ListType)

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    Public ReadOnly Property SampleInListCollection() As ObjectSet(Of SampleInList)
        Get
            If (_SampleInListCollection Is Nothing) Then
                _SampleInListCollection = MyBase.CreateObjectSet(Of SampleInList)("SampleInListCollection")
            End If
            Return _SampleInListCollection
        End Get
    End Property

    Private _SampleInListCollection As ObjectSet(Of SampleInList)

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    Public ReadOnly Property SampleParameterCollection() As ObjectSet(Of SampleParameter)
        Get
            If (_SampleParameterCollection Is Nothing) Then
                _SampleParameterCollection = MyBase.CreateObjectSet(Of SampleParameter)("SampleParameterCollection")
            End If
            Return _SampleParameterCollection
        End Get
    End Property

    Private _SampleParameterCollection As ObjectSet(Of SampleParameter)

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    Public ReadOnly Property SampleListParameterCollection() As ObjectSet(Of SampleListParameter)
        Get
            If (_SampleListParameterCollection Is Nothing) Then
                _SampleListParameterCollection = MyBase.CreateObjectSet(Of SampleListParameter)("SampleListParameterCollection")
            End If
            Return _SampleListParameterCollection
        End Get
    End Property

    Private _SampleListParameterCollection As ObjectSet(Of SampleListParameter)

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    Public ReadOnly Property SampleAndListCollection() As ObjectSet(Of SampleAndList)
        Get
            If (_SampleAndListCollection Is Nothing) Then
                _SampleAndListCollection = MyBase.CreateObjectSet(Of SampleAndList)("SampleAndListCollection")
            End If
            Return _SampleAndListCollection
        End Get
    End Property

    Private _SampleAndListCollection As ObjectSet(Of SampleAndList)

    #End Region

    #Region "Методы AddTo"

    ''' <summary>
    ''' Устаревший метод для добавления новых объектов в набор EntitySet SampleListCollection. Взамен можно использовать метод .Add связанного свойства ObjectSet(Of T).
    ''' </summary>
    Public Sub AddToSampleListCollection(ByVal sampleList As SampleList)
        MyBase.AddObject("SampleListCollection", sampleList)
    End Sub

    ''' <summary>
    ''' Устаревший метод для добавления новых объектов в набор EntitySet ListLineCollection. Взамен можно использовать метод .Add связанного свойства ObjectSet(Of T).
    ''' </summary>
    Public Sub AddToListLineCollection(ByVal listLine As ListLine)
        MyBase.AddObject("ListLineCollection", listLine)
    End Sub

    ''' <summary>
    ''' Устаревший метод для добавления новых объектов в набор EntitySet ListTypeCollection. Взамен можно использовать метод .Add связанного свойства ObjectSet(Of T).
    ''' </summary>
    Public Sub AddToListTypeCollection(ByVal listType As ListType)
        MyBase.AddObject("ListTypeCollection", listType)
    End Sub

    ''' <summary>
    ''' Устаревший метод для добавления новых объектов в набор EntitySet SampleInListCollection. Взамен можно использовать метод .Add связанного свойства ObjectSet(Of T).
    ''' </summary>
    Public Sub AddToSampleInListCollection(ByVal sampleInList As SampleInList)
        MyBase.AddObject("SampleInListCollection", sampleInList)
    End Sub

    ''' <summary>
    ''' Устаревший метод для добавления новых объектов в набор EntitySet SampleParameterCollection. Взамен можно использовать метод .Add связанного свойства ObjectSet(Of T).
    ''' </summary>
    Public Sub AddToSampleParameterCollection(ByVal sampleParameter As SampleParameter)
        MyBase.AddObject("SampleParameterCollection", sampleParameter)
    End Sub

    ''' <summary>
    ''' Устаревший метод для добавления новых объектов в набор EntitySet SampleListParameterCollection. Взамен можно использовать метод .Add связанного свойства ObjectSet(Of T).
    ''' </summary>
    Public Sub AddToSampleListParameterCollection(ByVal sampleListParameter As SampleListParameter)
        MyBase.AddObject("SampleListParameterCollection", sampleListParameter)
    End Sub

    ''' <summary>
    ''' Устаревший метод для добавления новых объектов в набор EntitySet SampleAndListCollection. Взамен можно использовать метод .Add связанного свойства ObjectSet(Of T).
    ''' </summary>
    Public Sub AddToSampleAndListCollection(ByVal sampleAndList As SampleAndList)
        MyBase.AddObject("SampleAndListCollection", sampleAndList)
    End Sub

    #End Region

End Class

#End Region

#Region "Сущности"

''' <summary>
''' Нет доступной документации по метаданным.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ModelSampleList", Name:="ListLine")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class ListLine
    Inherits EntityObject
    #Region "Фабричный метод"

    ''' <summary>
    ''' Создание нового объекта ListLine.
    ''' </summary>
    ''' <param name="iDListLine">Исходное значение свойства IDListLine.</param>
    ''' <param name="listLineName">Исходное значение свойства ListLineName.</param>
    Public Shared Function CreateListLine(iDListLine As Global.System.Int32, listLineName As Global.System.String) As ListLine
        Dim listLine as ListLine = New ListLine
        listLine.IDListLine = iDListLine
        listLine.ListLineName = listLineName
        Return listLine
    End Function

    #End Region

    #Region "Свойства-примитивы"

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDListLine() As Global.System.Int32
        Get
            Return _IDListLine
        End Get
        Set
            If (_IDListLine <> Value) Then
                OnIDListLineChanging(value)
                ReportPropertyChanging("IDListLine")
                _IDListLine = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDListLine")
                OnIDListLineChanged()
            End If
        End Set
    End Property

    Private _IDListLine As Global.System.Int32
    Private Partial Sub OnIDListLineChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDListLineChanged()
    End Sub

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ListLineName() As Global.System.String
        Get
            Return _ListLineName
        End Get
        Set
            OnListLineNameChanging(value)
            ReportPropertyChanging("ListLineName")
            _ListLineName = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("ListLineName")
            OnListLineNameChanged()
        End Set
    End Property

    Private _ListLineName As Global.System.String
    Private Partial Sub OnListLineNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnListLineNameChanged()
    End Sub

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IsActiveFlag() As Global.System.Boolean
        Get
            Return _IsActiveFlag
        End Get
        Set
            OnIsActiveFlagChanging(value)
            ReportPropertyChanging("IsActiveFlag")
            _IsActiveFlag = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IsActiveFlag")
            OnIsActiveFlagChanged()
        End Set
    End Property

    Private _IsActiveFlag As Global.System.Boolean = true
    Private Partial Sub OnIsActiveFlagChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnIsActiveFlagChanged()
    End Sub

    #End Region

    #Region "Свойства навигации"

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModelSampleList", "ListLineSampleList", "SampleList")>
     Public Property SampleList() As EntityCollection(Of SampleList)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of SampleList)("ModelSampleList.ListLineSampleList", "SampleList")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of SampleList)("ModelSampleList.ListLineSampleList", "SampleList", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' Нет доступной документации по метаданным.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ModelSampleList", Name:="ListType")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class ListType
    Inherits EntityObject
    #Region "Фабричный метод"

    ''' <summary>
    ''' Создание нового объекта ListType.
    ''' </summary>
    ''' <param name="iDListType">Исходное значение свойства IDListType.</param>
    ''' <param name="listTypeName">Исходное значение свойства ListTypeName.</param>
    Public Shared Function CreateListType(iDListType As Global.System.Int32, listTypeName As Global.System.String) As ListType
        Dim listType as ListType = New ListType
        listType.IDListType = iDListType
        listType.ListTypeName = listTypeName
        Return listType
    End Function

    #End Region

    #Region "Свойства-примитивы"

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDListType() As Global.System.Int32
        Get
            Return _IDListType
        End Get
        Set
            If (_IDListType <> Value) Then
                OnIDListTypeChanging(value)
                ReportPropertyChanging("IDListType")
                _IDListType = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDListType")
                OnIDListTypeChanged()
            End If
        End Set
    End Property

    Private _IDListType As Global.System.Int32
    Private Partial Sub OnIDListTypeChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDListTypeChanged()
    End Sub

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ListTypeName() As Global.System.String
        Get
            Return _ListTypeName
        End Get
        Set
            OnListTypeNameChanging(value)
            ReportPropertyChanging("ListTypeName")
            _ListTypeName = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("ListTypeName")
            OnListTypeNameChanged()
        End Set
    End Property

    Private _ListTypeName As Global.System.String
    Private Partial Sub OnListTypeNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnListTypeNameChanged()
    End Sub

    #End Region

    #Region "Свойства навигации"

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModelSampleList", "ListTypeSampleList", "SampleList")>
     Public Property SampleList() As EntityCollection(Of SampleList)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of SampleList)("ModelSampleList.ListTypeSampleList", "SampleList")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of SampleList)("ModelSampleList.ListTypeSampleList", "SampleList", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' Нет доступной документации по метаданным.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ModelSampleList", Name:="SampleAndList")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class SampleAndList
    Inherits EntityObject
    #Region "Фабричный метод"

    ''' <summary>
    ''' Создание нового объекта SampleAndList.
    ''' </summary>
    ''' <param name="id">Исходное значение свойства ID.</param>
    ''' <param name="iDSample">Исходное значение свойства IDSample.</param>
    ''' <param name="iDList">Исходное значение свойства IDList.</param>
    Public Shared Function CreateSampleAndList(id As Global.System.Int32, iDSample As Global.System.Int32, iDList As Global.System.Int32) As SampleAndList
        Dim sampleAndList as SampleAndList = New SampleAndList
        sampleAndList.ID = id
        sampleAndList.IDSample = iDSample
        sampleAndList.IDList = iDList
        Return sampleAndList
    End Function

    #End Region

    #Region "Свойства-примитивы"

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ID() As Global.System.Int32
        Get
            Return _ID
        End Get
        Set
            If (_ID <> Value) Then
                OnIDChanging(value)
                ReportPropertyChanging("ID")
                _ID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ID")
                OnIDChanged()
            End If
        End Set
    End Property

    Private _ID As Global.System.Int32
    Private Partial Sub OnIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDChanged()
    End Sub

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDSample() As Global.System.Int32
        Get
            Return _IDSample
        End Get
        Set
            OnIDSampleChanging(value)
            ReportPropertyChanging("IDSample")
            _IDSample = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IDSample")
            OnIDSampleChanged()
        End Set
    End Property

    Private _IDSample As Global.System.Int32
    Private Partial Sub OnIDSampleChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDSampleChanged()
    End Sub

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDList() As Global.System.Int32
        Get
            Return _IDList
        End Get
        Set
            OnIDListChanging(value)
            ReportPropertyChanging("IDList")
            _IDList = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IDList")
            OnIDListChanged()
        End Set
    End Property

    Private _IDList As Global.System.Int32
    Private Partial Sub OnIDListChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDListChanged()
    End Sub

    #End Region

    #Region "Свойства навигации"

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModelSampleList", "SampleInListSampleAndList", "SampleInList")>
    Public Property SampleInList() As SampleInList
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SampleInList)("ModelSampleList.SampleInListSampleAndList", "SampleInList").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SampleInList)("ModelSampleList.SampleInListSampleAndList", "SampleInList").Value = value
        End Set
    End Property
    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property SampleInListReference() As EntityReference(Of SampleInList)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SampleInList)("ModelSampleList.SampleInListSampleAndList", "SampleInList")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of SampleInList)("ModelSampleList.SampleInListSampleAndList", "SampleInList", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModelSampleList", "SampleListSampleAndList", "SampleList")>
    Public Property SampleList() As SampleList
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SampleList)("ModelSampleList.SampleListSampleAndList", "SampleList").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SampleList)("ModelSampleList.SampleListSampleAndList", "SampleList").Value = value
        End Set
    End Property
    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property SampleListReference() As EntityReference(Of SampleList)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SampleList)("ModelSampleList.SampleListSampleAndList", "SampleList")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of SampleList)("ModelSampleList.SampleListSampleAndList", "SampleList", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' Нет доступной документации по метаданным.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ModelSampleList", Name:="SampleInList")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class SampleInList
    Inherits EntityObject
    #Region "Фабричный метод"

    ''' <summary>
    ''' Создание нового объекта SampleInList.
    ''' </summary>
    ''' <param name="iDSample">Исходное значение свойства IDSample.</param>
    Public Shared Function CreateSampleInList(iDSample As Global.System.Int32) As SampleInList
        Dim sampleInList as SampleInList = New SampleInList
        sampleInList.IDSample = iDSample
        Return sampleInList
    End Function

    #End Region

    #Region "Свойства-примитивы"

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDSample() As Global.System.Int32
        Get
            Return _IDSample
        End Get
        Set
            If (_IDSample <> Value) Then
                OnIDSampleChanging(value)
                ReportPropertyChanging("IDSample")
                _IDSample = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDSample")
                OnIDSampleChanged()
            End If
        End Set
    End Property

    Private _IDSample As Global.System.Int32
    Private Partial Sub OnIDSampleChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDSampleChanged()
    End Sub

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property SampleNumber() As Global.System.String
        Get
            Return _SampleNumber
        End Get
        Set
            OnSampleNumberChanging(value)
            ReportPropertyChanging("SampleNumber")
            _SampleNumber = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("SampleNumber")
            OnSampleNumberChanged()
        End Set
    End Property

    Private _SampleNumber As Global.System.String
    Private Partial Sub OnSampleNumberChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnSampleNumberChanged()
    End Sub

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IsLockedFlag() As Global.System.Boolean
        Get
            Return _IsLockedFlag
        End Get
        Set
            OnIsLockedFlagChanging(value)
            ReportPropertyChanging("IsLockedFlag")
            _IsLockedFlag = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IsLockedFlag")
            OnIsLockedFlagChanged()
        End Set
    End Property

    Private _IsLockedFlag As Global.System.Boolean = false
    Private Partial Sub OnIsLockedFlagChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnIsLockedFlagChanged()
    End Sub

    #End Region

    #Region "Свойства навигации"

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModelSampleList", "SampleInListSampleParameter", "SampleParameter")>
     Public Property SampleParameter() As EntityCollection(Of SampleParameter)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of SampleParameter)("ModelSampleList.SampleInListSampleParameter", "SampleParameter")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of SampleParameter)("ModelSampleList.SampleInListSampleParameter", "SampleParameter", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModelSampleList", "SampleInListSampleAndList", "SampleAndList")>
     Public Property SampleAndList() As EntityCollection(Of SampleAndList)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of SampleAndList)("ModelSampleList.SampleInListSampleAndList", "SampleAndList")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of SampleAndList)("ModelSampleList.SampleInListSampleAndList", "SampleAndList", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' Нет доступной документации по метаданным.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ModelSampleList", Name:="SampleList")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class SampleList
    Inherits EntityObject
    #Region "Фабричный метод"

    ''' <summary>
    ''' Создание нового объекта SampleList.
    ''' </summary>
    ''' <param name="iDList">Исходное значение свойства IDList.</param>
    ''' <param name="listName">Исходное значение свойства ListName.</param>
    ''' <param name="openDate">Исходное значение свойства OpenDate.</param>
    Public Shared Function CreateSampleList(iDList As Global.System.Int32, listName As Global.System.String, openDate As Global.System.DateTime) As SampleList
        Dim sampleList as SampleList = New SampleList
        sampleList.IDList = iDList
        sampleList.ListName = listName
        sampleList.OpenDate = openDate
        Return sampleList
    End Function

    #End Region

    #Region "Свойства-примитивы"

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDList() As Global.System.Int32
        Get
            Return _IDList
        End Get
        Set
            If (_IDList <> Value) Then
                OnIDListChanging(value)
                ReportPropertyChanging("IDList")
                _IDList = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDList")
                OnIDListChanged()
            End If
        End Set
    End Property

    Private _IDList As Global.System.Int32
    Private Partial Sub OnIDListChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDListChanged()
    End Sub

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ListName() As Global.System.String
        Get
            Return _ListName
        End Get
        Set
            OnListNameChanging(value)
            ReportPropertyChanging("ListName")
            _ListName = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("ListName")
            OnListNameChanged()
        End Set
    End Property

    Private _ListName As Global.System.String
    Private Partial Sub OnListNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnListNameChanged()
    End Sub

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property IDListLine() As Nullable(Of Global.System.Int32)
        Get
            Return _IDListLine
        End Get
        Set
            OnIDListLineChanging(value)
            ReportPropertyChanging("IDListLine")
            _IDListLine = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IDListLine")
            OnIDListLineChanged()
        End Set
    End Property

    Private _IDListLine As Nullable(Of Global.System.Int32)
    Private Partial Sub OnIDListLineChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnIDListLineChanged()
    End Sub

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property IDListType() As Nullable(Of Global.System.Int32)
        Get
            Return _IDListType
        End Get
        Set
            OnIDListTypeChanging(value)
            ReportPropertyChanging("IDListType")
            _IDListType = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IDListType")
            OnIDListTypeChanged()
        End Set
    End Property

    Private _IDListType As Nullable(Of Global.System.Int32)
    Private Partial Sub OnIDListTypeChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnIDListTypeChanged()
    End Sub

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IsActiveFlag() As Global.System.Boolean
        Get
            Return _IsActiveFlag
        End Get
        Set
            OnIsActiveFlagChanging(value)
            ReportPropertyChanging("IsActiveFlag")
            _IsActiveFlag = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IsActiveFlag")
            OnIsActiveFlagChanged()
        End Set
    End Property

    Private _IsActiveFlag As Global.System.Boolean = true
    Private Partial Sub OnIsActiveFlagChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnIsActiveFlagChanged()
    End Sub

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property OpenDate() As Global.System.DateTime
        Get
            Return _OpenDate
        End Get
        Set
            OnOpenDateChanging(value)
            ReportPropertyChanging("OpenDate")
            _OpenDate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("OpenDate")
            OnOpenDateChanged()
        End Set
    End Property

    Private _OpenDate As Global.System.DateTime
    Private Partial Sub OnOpenDateChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnOpenDateChanged()
    End Sub

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CloseDate() As Nullable(Of Global.System.DateTime)
        Get
            Return _CloseDate
        End Get
        Set
            OnCloseDateChanging(value)
            ReportPropertyChanging("CloseDate")
            _CloseDate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("CloseDate")
            OnCloseDateChanged()
        End Set
    End Property

    Private _CloseDate As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnCloseDateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnCloseDateChanged()
    End Sub

    #End Region

    #Region "Свойства навигации"

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModelSampleList", "ListLineSampleList", "ListLine")>
    Public Property ListLine() As ListLine
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of ListLine)("ModelSampleList.ListLineSampleList", "ListLine").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of ListLine)("ModelSampleList.ListLineSampleList", "ListLine").Value = value
        End Set
    End Property
    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property ListLineReference() As EntityReference(Of ListLine)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of ListLine)("ModelSampleList.ListLineSampleList", "ListLine")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of ListLine)("ModelSampleList.ListLineSampleList", "ListLine", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModelSampleList", "ListTypeSampleList", "ListType")>
    Public Property ListType() As ListType
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of ListType)("ModelSampleList.ListTypeSampleList", "ListType").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of ListType)("ModelSampleList.ListTypeSampleList", "ListType").Value = value
        End Set
    End Property
    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property ListTypeReference() As EntityReference(Of ListType)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of ListType)("ModelSampleList.ListTypeSampleList", "ListType")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of ListType)("ModelSampleList.ListTypeSampleList", "ListType", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModelSampleList", "SampleListSampleListParameter", "SampleListParameter")>
     Public Property SampleListParameter() As EntityCollection(Of SampleListParameter)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of SampleListParameter)("ModelSampleList.SampleListSampleListParameter", "SampleListParameter")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of SampleListParameter)("ModelSampleList.SampleListSampleListParameter", "SampleListParameter", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModelSampleList", "SampleListSampleAndList", "SampleAndList")>
     Public Property SampleAndList() As EntityCollection(Of SampleAndList)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of SampleAndList)("ModelSampleList.SampleListSampleAndList", "SampleAndList")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of SampleAndList)("ModelSampleList.SampleListSampleAndList", "SampleAndList", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' Нет доступной документации по метаданным.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ModelSampleList", Name:="SampleListParameter")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class SampleListParameter
    Inherits EntityObject
    #Region "Фабричный метод"

    ''' <summary>
    ''' Создание нового объекта SampleListParameter.
    ''' </summary>
    ''' <param name="iDLParameter">Исходное значение свойства IDLParameter.</param>
    ''' <param name="parameterName">Исходное значение свойства ParameterName.</param>
    ''' <param name="parameterValue">Исходное значение свойства ParameterValue.</param>
    ''' <param name="parameterNETtype">Исходное значение свойства ParameterNETtype.</param>
    ''' <param name="iDList">Исходное значение свойства IDList.</param>
    Public Shared Function CreateSampleListParameter(iDLParameter As Global.System.Int32, parameterName As Global.System.String, parameterValue As Global.System.String, parameterNETtype As Global.System.String, iDList As Global.System.Int32) As SampleListParameter
        Dim sampleListParameter as SampleListParameter = New SampleListParameter
        sampleListParameter.IDLParameter = iDLParameter
        sampleListParameter.ParameterName = parameterName
        sampleListParameter.ParameterValue = parameterValue
        sampleListParameter.ParameterNETtype = parameterNETtype
        sampleListParameter.IDList = iDList
        Return sampleListParameter
    End Function

    #End Region

    #Region "Свойства-примитивы"

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDLParameter() As Global.System.Int32
        Get
            Return _IDLParameter
        End Get
        Set
            If (_IDLParameter <> Value) Then
                OnIDLParameterChanging(value)
                ReportPropertyChanging("IDLParameter")
                _IDLParameter = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDLParameter")
                OnIDLParameterChanged()
            End If
        End Set
    End Property

    Private _IDLParameter As Global.System.Int32
    Private Partial Sub OnIDLParameterChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDLParameterChanged()
    End Sub

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ParameterName() As Global.System.String
        Get
            Return _ParameterName
        End Get
        Set
            OnParameterNameChanging(value)
            ReportPropertyChanging("ParameterName")
            _ParameterName = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("ParameterName")
            OnParameterNameChanged()
        End Set
    End Property

    Private _ParameterName As Global.System.String
    Private Partial Sub OnParameterNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnParameterNameChanged()
    End Sub

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ParameterValue() As Global.System.String
        Get
            Return _ParameterValue
        End Get
        Set
            OnParameterValueChanging(value)
            ReportPropertyChanging("ParameterValue")
            _ParameterValue = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("ParameterValue")
            OnParameterValueChanged()
        End Set
    End Property

    Private _ParameterValue As Global.System.String
    Private Partial Sub OnParameterValueChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnParameterValueChanged()
    End Sub

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ParameterType() As Global.System.String
        Get
            Return _ParameterType
        End Get
        Set
            OnParameterTypeChanging(value)
            ReportPropertyChanging("ParameterType")
            _ParameterType = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("ParameterType")
            OnParameterTypeChanged()
        End Set
    End Property

    Private _ParameterType As Global.System.String
    Private Partial Sub OnParameterTypeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnParameterTypeChanged()
    End Sub

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ParameterNETtype() As Global.System.String
        Get
            Return _ParameterNETtype
        End Get
        Set
            OnParameterNETtypeChanging(value)
            ReportPropertyChanging("ParameterNETtype")
            _ParameterNETtype = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("ParameterNETtype")
            OnParameterNETtypeChanged()
        End Set
    End Property

    Private _ParameterNETtype As Global.System.String
    Private Partial Sub OnParameterNETtypeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnParameterNETtypeChanged()
    End Sub

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDList() As Global.System.Int32
        Get
            Return _IDList
        End Get
        Set
            OnIDListChanging(value)
            ReportPropertyChanging("IDList")
            _IDList = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IDList")
            OnIDListChanged()
        End Set
    End Property

    Private _IDList As Global.System.Int32
    Private Partial Sub OnIDListChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDListChanged()
    End Sub

    #End Region

    #Region "Свойства навигации"

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModelSampleList", "SampleListSampleListParameter", "SampleList")>
    Public Property SampleList() As SampleList
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SampleList)("ModelSampleList.SampleListSampleListParameter", "SampleList").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SampleList)("ModelSampleList.SampleListSampleListParameter", "SampleList").Value = value
        End Set
    End Property
    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property SampleListReference() As EntityReference(Of SampleList)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SampleList)("ModelSampleList.SampleListSampleListParameter", "SampleList")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of SampleList)("ModelSampleList.SampleListSampleListParameter", "SampleList", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' Нет доступной документации по метаданным.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ModelSampleList", Name:="SampleParameter")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class SampleParameter
    Inherits EntityObject
    #Region "Фабричный метод"

    ''' <summary>
    ''' Создание нового объекта SampleParameter.
    ''' </summary>
    ''' <param name="iDSParameter">Исходное значение свойства IDSParameter.</param>
    ''' <param name="parameterName">Исходное значение свойства ParameterName.</param>
    ''' <param name="parameterValue">Исходное значение свойства ParameterValue.</param>
    ''' <param name="parameterNETtype">Исходное значение свойства ParameterNETtype.</param>
    ''' <param name="iDSample">Исходное значение свойства IDSample.</param>
    Public Shared Function CreateSampleParameter(iDSParameter As Global.System.Int32, parameterName As Global.System.String, parameterValue As Global.System.String, parameterNETtype As Global.System.String, iDSample As Global.System.Int32) As SampleParameter
        Dim sampleParameter as SampleParameter = New SampleParameter
        sampleParameter.IDSParameter = iDSParameter
        sampleParameter.ParameterName = parameterName
        sampleParameter.ParameterValue = parameterValue
        sampleParameter.ParameterNETtype = parameterNETtype
        sampleParameter.IDSample = iDSample
        Return sampleParameter
    End Function

    #End Region

    #Region "Свойства-примитивы"

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDSParameter() As Global.System.Int32
        Get
            Return _IDSParameter
        End Get
        Set
            If (_IDSParameter <> Value) Then
                OnIDSParameterChanging(value)
                ReportPropertyChanging("IDSParameter")
                _IDSParameter = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDSParameter")
                OnIDSParameterChanged()
            End If
        End Set
    End Property

    Private _IDSParameter As Global.System.Int32
    Private Partial Sub OnIDSParameterChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDSParameterChanged()
    End Sub

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ParameterName() As Global.System.String
        Get
            Return _ParameterName
        End Get
        Set
            OnParameterNameChanging(value)
            ReportPropertyChanging("ParameterName")
            _ParameterName = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("ParameterName")
            OnParameterNameChanged()
        End Set
    End Property

    Private _ParameterName As Global.System.String
    Private Partial Sub OnParameterNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnParameterNameChanged()
    End Sub

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ParameterValue() As Global.System.String
        Get
            Return _ParameterValue
        End Get
        Set
            OnParameterValueChanging(value)
            ReportPropertyChanging("ParameterValue")
            _ParameterValue = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("ParameterValue")
            OnParameterValueChanged()
        End Set
    End Property

    Private _ParameterValue As Global.System.String
    Private Partial Sub OnParameterValueChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnParameterValueChanged()
    End Sub

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ParameterType() As Global.System.String
        Get
            Return _ParameterType
        End Get
        Set
            OnParameterTypeChanging(value)
            ReportPropertyChanging("ParameterType")
            _ParameterType = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("ParameterType")
            OnParameterTypeChanged()
        End Set
    End Property

    Private _ParameterType As Global.System.String
    Private Partial Sub OnParameterTypeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnParameterTypeChanged()
    End Sub

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ParameterNETtype() As Global.System.String
        Get
            Return _ParameterNETtype
        End Get
        Set
            OnParameterNETtypeChanging(value)
            ReportPropertyChanging("ParameterNETtype")
            _ParameterNETtype = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("ParameterNETtype")
            OnParameterNETtypeChanged()
        End Set
    End Property

    Private _ParameterNETtype As Global.System.String
    Private Partial Sub OnParameterNETtypeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnParameterNETtypeChanged()
    End Sub

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDSample() As Global.System.Int32
        Get
            Return _IDSample
        End Get
        Set
            OnIDSampleChanging(value)
            ReportPropertyChanging("IDSample")
            _IDSample = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IDSample")
            OnIDSampleChanged()
        End Set
    End Property

    Private _IDSample As Global.System.Int32
    Private Partial Sub OnIDSampleChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDSampleChanged()
    End Sub

    #End Region

    #Region "Свойства навигации"

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModelSampleList", "SampleInListSampleParameter", "SampleInList")>
    Public Property SampleInList() As SampleInList
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SampleInList)("ModelSampleList.SampleInListSampleParameter", "SampleInList").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SampleInList)("ModelSampleList.SampleInListSampleParameter", "SampleInList").Value = value
        End Set
    End Property
    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property SampleInListReference() As EntityReference(Of SampleInList)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SampleInList)("ModelSampleList.SampleInListSampleParameter", "SampleInList")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of SampleInList)("ModelSampleList.SampleInListSampleParameter", "SampleInList", value)
            End If
        End Set
    End Property

    #End Region

End Class

#End Region


