'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.21006.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.0.21006.1.
'
Namespace PhotoDriveMarker

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.21006.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=False)> _
    Partial Public Class PHOTODRIVEMARKER



        Private fOLDERField() As PHOTODRIVEMARKERFOLDER

        Private versionField As String
        Dim aCCESSField As PHOTODRIVEMARKERACCESS

        '''<remarks/>
        Public Property ACCESS() As PHOTODRIVEMARKERACCESS
            Get
                Return Me.aCCESSField
            End Get
            Set(ByVal value As PHOTODRIVEMARKERACCESS)
                Me.aCCESSField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("FOLDER")> _
        Public Property FOLDER() As PHOTODRIVEMARKERFOLDER()
            Get
                Return Me.fOLDERField
            End Get
            Set(ByVal value As PHOTODRIVEMARKERFOLDER())
                Me.fOLDERField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property version() As String
            Get
                Return Me.versionField
            End Get
            Set(ByVal value As String)
                Me.versionField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.21006.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
    Partial Public Class PHOTODRIVEMARKERACCESS

        Private accessField As access

        Private publickeyField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property access() As access
            Get
                Return Me.accessField
            End Get
            Set(ByVal value As access)
                Me.accessField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property publickey() As String
            Get
                Return Me.publickeyField
            End Get
            Set(ByVal value As String)
                Me.publickeyField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.21006.1"), _
     System.SerializableAttribute()> _
    Public Enum access

        '''<remarks/>
        [public]

        '''<remarks/>
        [private]
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.21006.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
    Partial Public Class PHOTODRIVEMARKERFOLDER

        Private sTRUCTUREDField As PHOTODRIVEMARKERFOLDERSTRUCTURED

        Private cONTENTSField As PHOTODRIVEMARKERFOLDERCONTENTS

        Private nameField As String

        Private accessField As access

        Private publickeyField As String

        '''<remarks/>
        Public Property STRUCTURED() As PHOTODRIVEMARKERFOLDERSTRUCTURED
            Get
                Return Me.sTRUCTUREDField
            End Get
            Set(ByVal value As PHOTODRIVEMARKERFOLDERSTRUCTURED)
                Me.sTRUCTUREDField = value
            End Set
        End Property




        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set(ByVal value As String)
                Me.nameField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property access() As access
            Get
                Return Me.accessField
            End Get
            Set(ByVal value As access)
                Me.accessField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property publickey() As String
            Get
                Return Me.publickeyField
            End Get
            Set(ByVal value As String)
                Me.publickeyField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.21006.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
    Partial Public Class PHOTODRIVEMARKERFOLDERSTRUCTURED

        Private lEVELField() As PHOTODRIVEMARKERFOLDERSTRUCTUREDLEVEL

        Private flagField As Boolean

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("LEVEL")> _
        Public Property LEVEL() As PHOTODRIVEMARKERFOLDERSTRUCTUREDLEVEL()
            Get
                Return Me.lEVELField
            End Get
            Set(ByVal value As PHOTODRIVEMARKERFOLDERSTRUCTUREDLEVEL())
                Me.lEVELField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property flag() As Boolean
            Get
                Return Me.flagField
            End Get
            Set(ByVal value As Boolean)
                Me.flagField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.21006.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
    Partial Public Class PHOTODRIVEMARKERFOLDERSTRUCTUREDLEVEL

        Private orderField As Byte

        Private templateField As String

        Private typeField As levelType

        Private valueField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property order() As Byte
            Get
                Return Me.orderField
            End Get
            Set(ByVal value As Byte)
                Me.orderField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property template() As String
            Get
                Return Me.templateField
            End Get
            Set(ByVal value As String)
                Me.templateField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property type() As levelType
            Get
                Return Me.typeField
            End Get
            Set(ByVal value As levelType)
                Me.typeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property value() As String
            Get
                Return Me.valueField
            End Get
            Set(ByVal value As String)
                Me.valueField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.21006.1"), _
     System.SerializableAttribute()> _
    Public Enum levelType

        '''<remarks/>
        virtual

        '''<remarks/>
        contents
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.21006.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
    Partial Public Class PHOTODRIVEMARKERFOLDERCONTENTS

        Private fILEField As PHOTODRIVEMARKERFOLDERCONTENTSFILE

        Private typeField As contentsType

        '''<remarks/>
        Public Property FILE() As PHOTODRIVEMARKERFOLDERCONTENTSFILE
            Get
                Return Me.fILEField
            End Get
            Set(ByVal value As PHOTODRIVEMARKERFOLDERCONTENTSFILE)
                Me.fILEField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property type() As contentsType
            Get
                Return Me.typeField
            End Get
            Set(ByVal value As contentsType)
                Me.typeField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.21006.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
    Partial Public Class PHOTODRIVEMARKERFOLDERCONTENTSFILE

        Private typeField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property type() As String
            Get
                Return Me.typeField
            End Get
            Set(ByVal value As String)
                Me.typeField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.21006.1"), _
     System.SerializableAttribute()> _
    Public Enum contentsType

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("EAN-13")> _
        EAN13

        '''<remarks/>
        [String]

        '''<remarks/>
        Digit

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("String-digit")> _
        Stringdigit
    End Enum
End Namespace
