'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.34209
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Этот класс создан автоматически классом StronglyTypedResourceBuilder
    'с помощью такого средства, как ResGen или Visual Studio.
    'Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    'с параметром /str или перестройте свой проект VS.
    '''<summary>
    '''  Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resource
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Service.Resource", GetType(Resource).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Перезаписывает свойство CurrentUICulture текущего потока для всех
        '''  обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;windows-1251&quot;?&gt;
        '''&lt;xs:schema xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot;&gt;
        '''  &lt;xsd:element name=&quot;AUCTIONAGENT&quot;&gt;
        '''    &lt;xsd:complexType&gt;
        '''      &lt;xsd:sequence&gt;
        '''        &lt;xsd:element maxOccurs=&quot;unbounded&quot; minOccurs=&quot;1&quot; name=&quot;AGENT&quot;&gt;
        '''          &lt;xsd:complexType&gt;
        '''            &lt;xsd:sequence&gt;
        '''              &lt;xsd:element maxOc [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property AgentsFields() As String
            Get
                Return ResourceManager.GetString("AgentsFields", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ImageSaved() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageSaved", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property noimage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noimage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        '''  &lt;xs:element name=&quot;USER&quot;&gt;
        '''    &lt;xs:complexType&gt;
        '''      &lt;xs:sequence&gt;
        '''        &lt;xs:element maxOccurs=&quot;unbounded&quot; name=&quot;WOKER&quot;&gt;
        '''          &lt;xs:complexType&gt;
        '''            &lt;xs:sequence&gt;
        '''              &lt;xs:element maxOccurs=&quot;unbounded&quot; name=&quot;OFFICEACCESS&quot;&gt;
        '''                &lt;xs:complexType&gt;
        '''                  &lt;xs:sequence minOccurs=&quot;0&quot;&gt;
        '''                [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property UserPermission() As String
            Get
                Return ResourceManager.GetString("UserPermission", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
